### ISSUE TITLE
Generate token for users connexion

### ISSUE THREAD

**Issue by FlorianJourde** [FlorianJourde/OpenClassrooms-5-Create-your-first-blog-in-PHP#46]
**Estimated time** : 2 h

**Comment by Zitna** [comment]
Bravo, c'est l'idée !
Attention à ton model/User qui doit être en phase avec ta base de données. Je ne vois pas token.
Ce serait bien d'avoir un temps possible d'usage du token en base. Tu pourras ainsi remplacer le contrôle fait sur la variable de session timeout. 
Attention à ta variable time, car, au bout de 30 minutes, la session est détruite, même si l'utilisateur est encore sur le site. Sinon, globalement, il vaut mieux utiliser DateTimeImmutable (DateTime) et vérifier avec un DateInterval, que d'utiliser time.

**Comment by FlorianJourde** [comment]
**Real time** : 1 h 30
**Note** : Also add mime type checking for posts images.
